contacts_index:
    path:     /
    defaults: { _controller: "ContactsBundle:Contacts:index" }
    methods:  GET

contacts_show:
    path:     /{id}/show
    defaults: { _controller: "ContactsBundle:Contacts:show" }
    methods:  GET

contacts_new:
    path:     /new
    defaults: { _controller: "ContactsBundle:Contacts:new" }
    methods:  [GET, POST]

contacts_edit:
    path:     /{id}/edit
    defaults: { _controller: "ContactsBundle:Contacts:edit" }
    methods:  [GET, POST]

contacts_delete:
    path:     /{id}/delete
    defaults: { _controller: "ContactsBundle:Contacts:delete" }
    methods:  DELETE
