EntitiesBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: EntitiesBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToMany:
      Contacts:
        targetEntity: Contacts
        joinTable:
          name: users_contacts
          joinColumns:
            user_id:
             referencedColumnName: id
          inverseJoinColumns:
           contact_id:
             referencedColumnName: id


    lifecycleCallbacks: {  }
